### ISSUE TITLE
有没有可能增加增加增量包的分解功能

### ISSUE THREAD

**Issue by skysumbra** [xzr467706992/FastbootEnhance#15]
![image](https://github.com/libxzr/FastbootEnhance/assets/24444616/0bb52bcf-179f-40d2-bb40-f96860d5ba8a)

目前工具不支援增量包的分解，请问有没有可能增加增量包的分解功能?

另外有找到https://github.com/vm03/payload_dumper  项目，类似这样?

**Comment by libxzr** [comment]
请选择 "Allow incremental" 。
增量包的分解不一定成功，完全得看运气，不过如果只是单纯的提取 boot 镜像，还是有一定成功概率的。
如果是要增量提取 system 之类的镜像，必须要有上一个版本的镜像作为基底，挺麻烦而且没什么用途，目前软件没有打算为此增加支持。
